//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::group::Entity as Group;
pub use super::local_auth::Entity as LocalAuth;
pub use super::project::Entity as Project;
pub use super::user::Entity as User;
pub use super::user_group_project::Entity as UserGroupProject;
